Repository AaronSosaRamos/ai-code-ds-assistant-frontend, pull requests merged in 2024-09, with the labels that each got.

#21 new nexamind form imp.
  app/nexamind/page.tsx
  components/data-structures/nexamind/Form.tsx
  package.json
  util/schemas/NexaMindSchema.ts
  yarn.lock
Labels: enhancement, help wanted, good first issue

#22 Ai assistant for software architecture - new updates
  app/nexamind/architecture-with-quality-attributes/page.tsx
  app/nexamind/architecture-with-requirements/page.tsx
  app/nexamind/improved-architecture/page.tsx
  app/nexamind/page.tsx
  components/data-structures/nexamind/ArchitectureDetails.tsx
  components/data-structures/nexamind/ArchitectureWithQualityAttributes.tsx
  components/data-structures/nexamind/ArchitectureWithRequirement.tsx
  components/data-structures/nexamind/Form.tsx
  components/data-structures/nexamind/ImprovedArchitecture.tsx
  package.json
  redux/architectureSlice.ts
  redux/store.ts
  util/schemas/NexaMindSchema.ts
  yarn.lock
Labels: documentation, enhancement, help wanted, good first issue, data-structures

#23 new screen imp. for nexamind
  app/page.tsx
  components/Navbar.tsx
Labels: documentation, enhancement, help wanted, data-structures

#24 Feature/codexpert
  app/codexpert/page.tsx
  app/nexamind/architecture-with-quality-attributes/page.tsx
  app/nexamind/architecture-with-requirements/page.tsx
  app/nexamind/improved-architecture/page.tsx
  app/nexamind/page.tsx
  components/codexpert/CodeXpertForm.tsx
  components/nexamind/ArchitectureDetails.tsx
  components/nexamind/ArchitectureWithQualityAttributes.tsx
  components/nexamind/ArchitectureWithRequirement.tsx
  components/nexamind/Form.tsx
  components/nexamind/ImprovedArchitecture.tsx
Labels: documentation, enhancement, help wanted, good first issue

#25 new main page imp.
  app/page.tsx
  components/Navbar.tsx
Labels: documentation, enhancement, good first issue
